### get file of image
http://localhost:5555/api/photos/img/lhszlupe-6iwxl

### get file of image with given history index (0 is oryginal file)
http://localhost:5555/api/photos/img/lht09s1l-fgdls?history=1

### get metadata of image
http://localhost:5555/api/photos/metadata/li1b743p-t9nqx

### get metadata of image with given history index (0 is oryginal file)
http://localhost:5555/api/photos/metadata/li1b743p-t9nqx?history=1
