### add rotate filter to a photo
PATCH http://localhost:5555/api/photos/filters

{
    "photoId": "<photoId>",
    "filter": "rotate",
    "filterArgs": 270
}

### add negate filter to a photo
PATCH http://localhost:5555/api/photos/filters

{
    "photoId": "<photoId>",
    "filter": "negate"
}

### flip a photo
PATCH http://localhost:5555/api/photos/filters

{
    "photoId": "<photoId>",
    "filter": "flip"
}
